-- Drop this file at:
-- react-native-gadget-shop/supabase/migrations/20260102000000_add_reviews.sql
--
-- Adds product reviews: star rating (1-5) + optional comment, one review
-- per user per product (they can edit it later, not spam new ones).

create table if not exists "public"."review" (
    "id" bigint generated by default as identity primary key,
    "created_at" timestamp with time zone not null default now(),
    "product" bigint not null references "public"."product"("id") on delete cascade,
    "user" uuid not null references "public"."users"("id") on delete cascade,
    "rating" smallint not null check (rating between 1 and 5),
    "comment" text,
    unique ("product", "user")
);

alter table "public"."review" enable row level security;

create policy "Reviews are readable by everyone"
on "public"."review" for select to authenticated
using (true);

create policy "Users can create their own review"
on "public"."review" for insert to authenticated
with check (auth.uid() = "user");

create policy "Users can update their own review"
on "public"."review" for update to authenticated
using (auth.uid() = "user")
with check (auth.uid() = "user");

create policy "Users can delete their own review"
on "public"."review" for delete to authenticated
using (auth.uid() = "user");

-- Convenience view: average rating + review count per product, so the
-- app doesn't have to pull every review row just to show a star average.
create or replace view "public"."product_rating_summary" as
select
    product,
    round(avg(rating)::numeric, 1) as average_rating,
    count(*) as review_count
from "public"."review"
group by product;
