-- Drop this file at:
-- react-native-gadget-shop/supabase/migrations/20260101000000_add_roles_rbac.sql
--
-- Adds a real roles system instead of the single `type = 'ADMIN'` string
-- check that existed before. Four roles are seeded:
--   super_admin  - full access, can manage admin accounts
--   admin        - can manage products/categories/orders
--   staff        - can manage orders only (no delete on products/categories)
--   customer     - regular shopper, default for all new signups
--
-- Backward compatibility: the old `users.type` column is kept and kept in
-- sync via trigger, so any code you haven't migrated yet that still checks
-- `type === 'ADMIN'` keeps working while you move screens over to role_id.

create table if not exists "public"."roles" (
    "id" bigint generated by default as identity primary key,
    "name" text not null unique,
    "description" text
);

insert into "public"."roles" (name, description) values
    ('super_admin', 'Full access, including managing admin accounts'),
    ('admin', 'Can manage products, categories, and orders'),
    ('staff', 'Can manage orders only'),
    ('customer', 'Regular shopper')
on conflict (name) do nothing;

alter table "public"."users"
    add column if not exists "role_id" bigint references "public"."roles"("id");

-- Backfill: existing ADMIN users -> 'admin' role, everyone else -> 'customer'
update "public"."users" u
set role_id = (select id from "public"."roles" where name = 'admin')
where u.type = 'ADMIN' and u.role_id is null;

update "public"."users" u
set role_id = (select id from "public"."roles" where name = 'customer')
where u.role_id is null;

alter table "public"."users" alter column "role_id" set default (
    select id from "public"."roles" where name = 'customer'
);

-- Helper used inside RLS policies: returns the caller's role name, or
-- 'customer' if somehow unset. SECURITY DEFINER so it can read the users
-- table regardless of the caller's own RLS visibility.
create or replace function "public"."current_user_role"()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  role_name text;
begin
  select r.name into role_name
  from public.users u
  join public.roles r on r.id = u.role_id
  where u.id = auth.uid();

  return coalesce(role_name, 'customer');
end;
$$;

-- Keep the legacy `type` column in sync whenever role_id changes, so any
-- not-yet-migrated `type = 'ADMIN'` checks continue to behave correctly.
create or replace function "public"."sync_legacy_type_from_role"()
returns trigger
language plpgsql
as $$
declare
  new_role_name text;
begin
  select name into new_role_name from public.roles where id = new.role_id;

  if new_role_name in ('super_admin', 'admin', 'staff') then
    new.type := 'ADMIN';
  else
    new.type := 'USER';
  end if;

  return new;
end;
$$;

drop trigger if exists "sync_legacy_type" on "public"."users";
create trigger "sync_legacy_type"
    before insert or update of role_id on "public"."users"
    for each row execute procedure "public"."sync_legacy_type_from_role"();

-- Replace the old ADMIN-only write policies with role-aware ones.
drop policy if exists "Enable insert for authenticated users only" on "public"."category";
drop policy if exists "Enable Update for Admins only" on "public"."category";
drop policy if exists "Enable Delete from Admins only" on "public"."category";

create policy "Category insert - admin and above"
on "public"."category" for insert to authenticated
with check (public.current_user_role() in ('super_admin', 'admin'));

create policy "Category update - admin and above"
on "public"."category" for update to authenticated
using (public.current_user_role() in ('super_admin', 'admin'))
with check (public.current_user_role() in ('super_admin', 'admin'));

create policy "Category delete - admin and above"
on "public"."category" for delete to authenticated
using (public.current_user_role() in ('super_admin', 'admin'));

drop policy if exists "Enable insert for admin users only" on "public"."product";
drop policy if exists "Enable update for auth users" on "public"."product";
drop policy if exists "Enable delete for Admins only" on "public"."product";

create policy "Product insert - admin and above"
on "public"."product" for insert to authenticated
with check (public.current_user_role() in ('super_admin', 'admin'));

create policy "Product update - staff and above"
on "public"."product" for update to authenticated
using (public.current_user_role() in ('super_admin', 'admin', 'staff'))
with check (public.current_user_role() in ('super_admin', 'admin', 'staff'));

create policy "Product delete - admin and above"
on "public"."product" for delete to authenticated
using (public.current_user_role() in ('super_admin', 'admin'));

-- Only super_admin can change another user's role.
-- IMPORTANT: an earlier migration (20250710201819_update-users-rls.sql)
-- created "Enable update for auth users" with `using (true)` — that must
-- be dropped, otherwise it stays active alongside this one and RLS
-- policies are OR'd together, so the old permissive rule would silently
-- let anyone update anyone's role_id regardless of this policy.
drop policy if exists "Enable update for auth users" on "public"."users";

create policy "Users can update their own non-role fields"
on "public"."users" for update to authenticated
using (auth.uid() = id)
with check (auth.uid() = id and role_id = (select role_id from public.users where id = auth.uid()));

create policy "Users role update - super_admin only"
on "public"."users" for update to authenticated
using (public.current_user_role() = 'super_admin')
with check (public.current_user_role() = 'super_admin');
